
import { randomUUID } from "node:crypto";

function aiConfig() {
  return {
    apiKey: process.env.FORGEOS_AI_API_KEY || "",
    baseUrl: (process.env.FORGEOS_AI_BASE_URL || "https://api.openai.com/v1").replace(/\/$/, ""),
    model: process.env.FORGEOS_AI_MODEL || "gpt-5.6",
    provider: process.env.FORGEOS_AI_PROVIDER || "openai-compatible",
  };
}

export function capabilities() {
  const c = aiConfig();
  return {
    ai: { configured: Boolean(c.apiKey), provider: c.provider, model: c.model },
    realExecution: true,
    repair: { available: Boolean(c.apiKey) },
    persistence: { canonicalSchema: true },
  };
}

function escapeHtml(value) {
  return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
}

function deterministicArtifacts(prompt) {
  const clean = String(prompt || "").trim().slice(0, 4000);
  const title = clean.split(/\s+/).slice(0, 8).join(" ") || "Generated Application";
  const safeTitle = escapeHtml(title);
  return [
    { path:"index.html", language:"html", content:'<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+safeTitle+'</title></head><body><div id="root"></div><script type="module" src="/src/main.jsx"></script></body></html>' },
    { path:"src/main.jsx", language:"jsx", content:'import React from "react";import{createRoot}from"react-dom/client";import"./styles.css";const requirement='+JSON.stringify(clean)+';function App(){return React.createElement("main",{className:"shell"},React.createElement("section",{className:"card"},React.createElement("div",{className:"eyebrow"},"FORGEOS GENERATED SOFTWARE"),React.createElement("h1",null,'+JSON.stringify(title)+'),React.createElement("p",null,"Generated source was verified by the real ForgeOS execution worker."),React.createElement("div",{className:"request"},React.createElement("strong",null,"Requirement"),React.createElement("p",null,requirement)),React.createElement("div",{className:"status"},"● Build verified")))}createRoot(document.getElementById("root")).render(React.createElement(App));' },
    { path:"src/styles.css", language:"css", content:'*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Inter,system-ui,sans-serif;background:#0b1020;color:#eef2ff}.shell{min-height:100vh;display:grid;place-items:center;padding:32px}.card{width:min(760px,100%);padding:32px;border:1px solid #26314d;border-radius:20px;background:#11182a}.eyebrow{font-size:11px;letter-spacing:.14em;color:#8ea4d8}h1{margin:12px 0;font-size:clamp(30px,6vw,48px)}p{color:#aeb9d2;line-height:1.6}.request{margin-top:24px;padding:18px;border-radius:14px;background:#0b1020;border:1px solid #26314d}.request p{white-space:pre-wrap}.status{margin-top:20px;color:#7ee2a8;font-weight:700}' },
    { path:"package.json", language:"json", content:JSON.stringify({name:"forgeos-generated-app",version:"0.1.0",private:true,type:"module",scripts:{build:"vite build"},dependencies:{react:"19.1.0","react-dom":"19.1.0"},devDependencies:{vite:"8.1.5","@vitejs/plugin-react":"latest"}},null,2) },
    { path:"vite.config.js", language:"js", content:'import{defineConfig}from"vite";import react from"@vitejs/plugin-react";export default defineConfig({plugins:[react()]});' },
    { path:"README.md", language:"markdown", content:"# "+title+"\\n\\nGenerated by ForgeOS.\\n\\nRequirement:\\n"+clean },
  ];
}

function validateArtifacts(artifacts) {
  if (!Array.isArray(artifacts) || artifacts.length < 5) throw new Error("invalid_generated_artifacts");
  const paths = new Set(artifacts.map((a)=>a.path));
  for (const required of ["index.html","src/main.jsx","package.json","vite.config.js"]) if (!paths.has(required)) throw new Error("missing_"+required);
  for (const file of artifacts) {
    if (!file || typeof file.path !== "string" || typeof file.content !== "string") throw new Error("invalid_generated_file");
    if (file.path.startsWith("/") || file.path.includes("..") || file.path.includes("\\")) throw new Error("unsafe_path");
  }
  const pkg = JSON.parse(artifacts.find((a)=>a.path==="package.json").content);
  if (pkg?.scripts?.preinstall || pkg?.scripts?.postinstall || pkg?.scripts?.prepare) throw new Error("lifecycle_scripts_not_allowed");
  if (String(pkg?.scripts?.build || "").trim() !== "vite build") throw new Error("unsupported_build_profile");
  return artifacts;
}

async function aiGenerate(prompt) {
  const c = aiConfig();
  if (!c.apiKey) return { artifacts: deterministicArtifacts(prompt), mode:"deterministic-fallback", provider:"deterministic", model:"deterministic-v4", usage:{} };
  const response = await fetch(c.baseUrl+"/chat/completions", {
    method:"POST",
    headers:{"content-type":"application/json",authorization:"Bearer "+c.apiKey},
    body:JSON.stringify({
      model:c.model,
      temperature:0.15,
      max_tokens:12000,
      messages:[
        {role:"system",content:"You are the ForgeOS code generation engine. Return JSON only. Generate a coherent runnable Vite React web app. Include index.html, src/main.jsx, src/styles.css, package.json, vite.config.js and README.md. Build script must be exactly vite build. Do not add lifecycle scripts, credentials, arbitrary server commands, or unavailable services."},
        {role:"user",content:"Build this requirement:\\n"+String(prompt).slice(0,4000)+'\\n\\nReturn a JSON object with an artifacts array; each artifact has path, language, and content.'}
      ],
      response_format:{type:"json_object"}
    })
  });
  const body = await response.json().catch(()=>({}));
  if (!response.ok) throw new Error(body?.error?.message || "ai_provider_http_"+response.status);
  const content = body?.choices?.[0]?.message?.content;
  if (typeof content !== "string") throw new Error("ai_provider_empty_response");
  let parsed; try { parsed=JSON.parse(content); } catch { throw new Error("ai_provider_invalid_json"); }
  return { artifacts:validateArtifacts(parsed.artifacts), mode:"ai", provider:c.provider, model:c.model, usage:body?.usage||{} };
}

export async function readProject(pool, slug) {
  if (!pool) throw new Error("worker_database_not_configured");
  const projectResult = await pool.query("select * from projects where slug=$1 limit 1", [slug]);
  const p = projectResult.rows[0];
  if (!p) return null;
  const runs = (await pool.query(
    "select id,prompt,provider,model,status,started_at,completed_at,tokens_in,tokens_out from ai_runs where project_id=$1 order by started_at desc limit 20",
    [p.id]
  )).rows;
  const runIds = runs.map((r) => r.id);
  const steps = runIds.length ? (await pool.query(
    "select id,run_id,title,detail,stage,risk,status,order_idx from ai_run_steps where run_id=any($1::uuid[]) order by order_idx",
    [runIds]
  )).rows : [];
  const events = runIds.length ? (await pool.query(
    "select id,run_id,level,stage,message,created_at from ai_events where run_id=any($1::uuid[]) order by created_at",
    [runIds]
  )).rows : [];
  const latest = (await pool.query(
    "select ss.id as snapshot_id,ss.created_at,sf.path,sf.language,sf.content from source_snapshots ss left join source_files sf on sf.snapshot_id=ss.id where ss.project_id=$1 order by ss.created_at desc,sf.path",
    [p.id]
  )).rows;
  const latestSnapshotId = latest[0]?.snapshot_id;
  const files = latest.filter((r) => r.snapshot_id === latestSnapshotId && r.path).map((r) => ({
    path: r.path, language: r.language || "text", content: r.content || ""
  }));
  return {
    project: {
      id: p.id, slug: p.slug, name: p.name, tagline: p.tagline, description: p.description,
      status: p.status, health: p.health, owner: p.owner, stack: p.stack || [],
      benchmark: Boolean(p.benchmark), createdAt: p.created_at, updatedAt: p.updated_at,
      runs: runs.map((run) => ({
        id: run.id, prompt: run.prompt, provider: run.provider, model: run.model,
        status: run.status, startedAt: run.started_at, completedAt: run.completed_at,
        tokensIn: run.tokens_in || 0, tokensOut: run.tokens_out || 0,
        plan: steps.filter((s) => s.run_id === run.id),
        events: events.filter((e) => e.run_id === run.id)
      })),
      generatedFiles: files,
      lastGeneratedAt: latestSnapshotId ? latest[0]?.created_at : null
    }
  };
}

export async function ensureSchema(pool) {
  if (!pool) return;
  await pool.query(
    'CREATE TABLE IF NOT EXISTS projects (id uuid PRIMARY KEY,slug varchar(255) UNIQUE NOT NULL,name varchar(255) NOT NULL,tagline text NOT NULL,description text NOT NULL,status varchar(50) NOT NULL,health varchar(50) NOT NULL,owner varchar(255) NOT NULL,stack jsonb NOT NULL,benchmark boolean DEFAULT false,preview_route varchar(255),preview_status varchar(50),preview_last_built_at timestamptz,created_at timestamptz DEFAULT now() NOT NULL,updated_at timestamptz DEFAULT now() NOT NULL);'+
    'CREATE TABLE IF NOT EXISTS project_brain_versions (id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,version integer NOT NULL,vision text NOT NULL,requirements jsonb NOT NULL,decisions jsonb NOT NULL,architecture jsonb NOT NULL,"schema" jsonb NOT NULL,integrations jsonb NOT NULL,created_at timestamptz DEFAULT now() NOT NULL);'+
    'CREATE TABLE IF NOT EXISTS pipeline_stages (id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,stage_id varchar(50) NOT NULL,label varchar(100) NOT NULL,status varchar(50) NOT NULL,summary text NOT NULL,progress integer NOT NULL,updated_at timestamptz DEFAULT now() NOT NULL);'+
    'CREATE TABLE IF NOT EXISTS source_snapshots (id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,commit_sha varchar(255),message text,created_at timestamptz DEFAULT now() NOT NULL);'+
    'CREATE TABLE IF NOT EXISTS source_files (id uuid PRIMARY KEY,snapshot_id uuid NOT NULL REFERENCES source_snapshots(id) ON DELETE CASCADE,path text NOT NULL,kind varchar(50) NOT NULL,language varchar(50),loc integer,status varchar(50),content text);'+
    'CREATE TABLE IF NOT EXISTS ai_runs (id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,prompt text NOT NULL,provider varchar(100) NOT NULL,model varchar(100) NOT NULL,status varchar(50) NOT NULL,tokens_in integer NOT NULL DEFAULT 0,tokens_out integer NOT NULL DEFAULT 0,started_at timestamptz DEFAULT now() NOT NULL,completed_at timestamptz);'+
    'CREATE TABLE IF NOT EXISTS ai_run_steps (id uuid PRIMARY KEY,run_id uuid NOT NULL REFERENCES ai_runs(id) ON DELETE CASCADE,title varchar(255) NOT NULL,detail text NOT NULL,stage varchar(50) NOT NULL,risk varchar(50) NOT NULL,status varchar(50) NOT NULL,order_idx integer NOT NULL);'+
    'CREATE TABLE IF NOT EXISTS ai_events (id uuid PRIMARY KEY,run_id uuid NOT NULL REFERENCES ai_runs(id) ON DELETE CASCADE,level varchar(50) NOT NULL,stage varchar(50) NOT NULL,message text NOT NULL,created_at timestamptz DEFAULT now() NOT NULL);'+
    'CREATE TABLE IF NOT EXISTS approvals (id uuid PRIMARY KEY,step_id uuid NOT NULL REFERENCES ai_run_steps(id) ON DELETE CASCADE,decision varchar(50) NOT NULL,actor varchar(255) NOT NULL,created_at timestamptz DEFAULT now() NOT NULL);'+
    'CREATE TABLE IF NOT EXISTS test_runs (id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,snapshot_id uuid REFERENCES source_snapshots(id),status varchar(50) NOT NULL,created_at timestamptz DEFAULT now() NOT NULL);'+
    'CREATE TABLE IF NOT EXISTS test_results (id uuid PRIMARY KEY,test_run_id uuid NOT NULL REFERENCES test_runs(id) ON DELETE CASCADE,name varchar(255) NOT NULL,suite varchar(50) NOT NULL,status varchar(50) NOT NULL,duration_ms integer NOT NULL,detail text);'+
    'CREATE TABLE IF NOT EXISTS deployments (id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,env varchar(50) NOT NULL,status varchar(50) NOT NULL,commit_sha varchar(255),url varchar(255) NOT NULL,adapter varchar(100) NOT NULL,created_at timestamptz DEFAULT now() NOT NULL);'+
    'CREATE TABLE IF NOT EXISTS audit_events (id uuid PRIMARY KEY,project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,actor varchar(50) NOT NULL,actor_name varchar(255) NOT NULL,action varchar(255) NOT NULL,target varchar(255) NOT NULL,risk varchar(50) NOT NULL,approved boolean,diff_summary text,stage varchar(50),created_at timestamptz DEFAULT now() NOT NULL);'
  );
}

async function ensureProject(pool, slug, prompt) {
  const id=randomUUID();
  const name=slug==="forgeos"?"ForgeOS":slug.replace(/[-_]+/g," ").replace(/\b\w/g,(m)=>m.toUpperCase());
  const r=await pool.query(
    "INSERT INTO projects(id,slug,name,tagline,description,status,health,owner,stack,benchmark) VALUES($1,$2,$3,$4,$5,'building','healthy','forgeos',$6::jsonb,false) ON CONFLICT(slug) DO UPDATE SET updated_at=now() RETURNING id",
    [id,slug,name,"AI software factory","Project managed by ForgeOS. Initial requirement: "+String(prompt).slice(0,1000),JSON.stringify(["React","TypeScript","Vite"])]
  );
  return r.rows[0].id;
}

async function recordPlan(pool,runId) {
  const steps=[
    ["Understand requirement","Read the requirement and current project context.","brain","low","done"],
    ["Draft implementation plan","Translate the requirement into a bounded source change.","plan","low","done"],
    ["Generate source","Produce a coherent runnable source tree.","build","low","done"],
    ["Real build verification","Install dependencies under policy and run the allowed build command.","test","low","running"],
    ["Review result","Record artifacts, tests, and audit evidence.","review","low","pending"]
  ];
  for(let i=0;i<steps.length;i++){const s=steps[i];await pool.query("INSERT INTO ai_run_steps(id,run_id,title,detail,stage,risk,status,order_idx) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",[randomUUID(),runId,...s,i]);}
}

async function recordBuild(pool,{runId,projectSlug,prompt,artifacts,result,generation}) {
  if(!pool) return null;
  await ensureSchema(pool);
  const projectId=await ensureProject(pool,projectSlug||"forgeos",prompt);
  await pool.query("INSERT INTO ai_runs(id,project_id,prompt,provider,model,status,tokens_in,tokens_out) VALUES($1,$2,$3,$4,$5,'testing',$6,$7) ON CONFLICT(id) DO UPDATE SET status='testing'",[runId,projectId,prompt,generation.provider,generation.model,Number(generation.usage?.prompt_tokens||0),Number(generation.usage?.completion_tokens||0)]);
  await recordPlan(pool,runId);
  await pool.query("INSERT INTO ai_events(id,run_id,level,stage,message) VALUES($1,$2,'info','brain',$3)",[randomUUID(),runId,"Requirement accepted by ForgeOS."]);
  await pool.query("INSERT INTO ai_events(id,run_id,level,stage,message) VALUES($1,$2,'info','build',$3)",[randomUUID(),runId,"Source generated using "+generation.mode+"."]);
  const snapshotId=randomUUID();
  await pool.query("INSERT INTO source_snapshots(id,project_id,message) VALUES($1,$2,$3)",[snapshotId,projectId,"Generated source ("+generation.mode+") for run "+runId]);
  for(const file of artifacts) await pool.query("INSERT INTO source_files(id,snapshot_id,path,kind,language,loc,status,content) VALUES($1,$2,$3,'file',$4,$5,'generated',$6)",[randomUUID(),snapshotId,file.path,file.language||"text",String(file.content||"").split("\n").length,file.content]);
  const passed=result.state==="passed"&&result.simulated===false;
  const testRunId=randomUUID();
  await pool.query("INSERT INTO test_runs(id,project_id,snapshot_id,status) VALUES($1,$2,$3,$4)",[testRunId,projectId,snapshotId,passed?"passed":"failed"]);
  await pool.query("INSERT INTO test_results(id,test_run_id,name,suite,status,duration_ms,detail) VALUES($1,$2,'real build','execution',$3,$4,$5)",[randomUUID(),testRunId,passed?"passed":"failed",Number(result?.build?.durationMs||result?.install?.durationMs||0),JSON.stringify(result)]);
  await pool.query("INSERT INTO ai_events(id,run_id,level,stage,message) VALUES($1,$2,$3,'test',$4)",[randomUUID(),runId,passed?"info":"error",passed?"Real build verification passed.":"Real build verification failed during "+result.phase+"."]);
  await pool.query("INSERT INTO audit_events(id,project_id,actor,actor_name,action,target,risk,approved,diff_summary,stage) VALUES($1,$2,'system','ForgeOS',$3,$4,'low',NULL,$5,'test')",[randomUUID(),projectId,passed?"real_build_passed":"real_build_failed",runId,result.error||result.phase]);
  await pool.query("UPDATE ai_runs SET status=$2,completed_at=now() WHERE id=$1",[runId,passed?"review":"repairing"]);
  return {projectId,snapshotId};
}

export async function buildAndPersist(pool,{runId,projectSlug,prompt,execute}) {
  const generation=await aiGenerate(prompt);
  const result=await execute(runId,generation.artifacts);
  const persistence=await recordBuild(pool,{runId,projectSlug,prompt,artifacts:generation.artifacts,result,generation});
  return {...result,generationMode:generation.mode,provider:generation.provider,model:generation.model,sourceFiles:generation.artifacts,projectId:persistence?.projectId||null,snapshotId:persistence?.snapshotId||null};
}

export async function repairAndBuild({runId,prompt,files,failure,execute}) {
  const c=aiConfig();
  if(!c.apiKey) throw new Error("ai_provider_not_configured");
  const response=await fetch(c.baseUrl+"/chat/completions",{method:"POST",headers:{"content-type":"application/json",authorization:"Bearer "+c.apiKey},body:JSON.stringify({model:c.model,temperature:0.1,max_tokens:12000,messages:[{role:"system",content:"You are the ForgeOS bounded repair engine. Return JSON only. Repair the supplied Vite React application so npm run build succeeds. Preserve the requirement and useful behavior. Return the complete corrected file set. Keep build exactly vite build and do not add lifecycle scripts or credentials."},{role:"user",content:"Requirement:\\n"+String(prompt).slice(0,4000)+"\\n\\nFailure:\\n"+JSON.stringify(failure).slice(0,12000)+"\\n\\nCurrent source:\\n"+files.map((f)=>"--- "+f.path+" ---\\n"+f.content).join("\\n").slice(0,60000)}],response_format:{type:"json_object"}})});
  const body=await response.json().catch(()=>({}));
  if(!response.ok)throw new Error(body?.error?.message||"ai_repair_failed");
  const parsed=JSON.parse(body?.choices?.[0]?.message?.content||"{}");
  const artifacts=validateArtifacts(parsed.artifacts);
  const result=await execute(runId,artifacts);
  return {...result,repairSimulated:false,generationMode:"ai-repair",provider:c.provider,model:c.model,sourceFiles:artifacts};
}

export async function latestSource(pool, projectSlug) {
  if(!pool)return [];
  await ensureSchema(pool);
  const snap=await pool.query("SELECT ss.id FROM source_snapshots ss JOIN projects p ON p.id=ss.project_id WHERE p.slug=$1 ORDER BY ss.created_at DESC LIMIT 1",[projectSlug || "forgeos"]);
  if(!snap.rows[0])return [];
  const rows=await pool.query("SELECT path,content FROM source_files WHERE snapshot_id=$1 ORDER BY path",[snap.rows[0].id]);
  return rows.rows.map((r)=>({path:r.path,content:r.content}));
}
