/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as NewRouteImport } from './routes/new'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProjectsSlugIndexRouteImport } from './routes/projects.$slug.index'
import { Route as ProjectsSlugBrainRouteImport } from './routes/projects.$slug.brain'
import { Route as ProjectsSlugBuilderRouteImport } from './routes/projects.$slug.builder'
import { Route as ProjectsSlugDataRouteImport } from './routes/projects.$slug.data'
import { Route as ProjectsSlugDeployRouteImport } from './routes/projects.$slug.deploy'
import { Route as ProjectsSlugFilesRouteImport } from './routes/projects.$slug.files'
import { Route as ProjectsSlugHistoryRouteImport } from './routes/projects.$slug.history'
import { Route as ProjectsSlugIntegrationsRouteImport } from './routes/projects.$slug.integrations'
import { Route as ProjectsSlugPreviewRouteImport } from './routes/projects.$slug.preview'
import { Route as ProjectsSlugTestsRouteImport } from './routes/projects.$slug.tests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugIndexRoute = ProjectsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugBrainRoute = ProjectsSlugBrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugBuilderRoute = ProjectsSlugBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugDataRoute = ProjectsSlugDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugDeployRoute = ProjectsSlugDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugFilesRoute = ProjectsSlugFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugHistoryRoute = ProjectsSlugHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugIntegrationsRoute =
  ProjectsSlugIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => ProjectsSlugRoute,
  } as any)
const ProjectsSlugPreviewRoute = ProjectsSlugPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ProjectsSlugRoute,
} as any)
const ProjectsSlugTestsRoute = ProjectsSlugTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => ProjectsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/new': typeof NewRoute
  '/providers': typeof ProvidersRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/$slug/brain': typeof ProjectsSlugBrainRoute
  '/projects/$slug/builder': typeof ProjectsSlugBuilderRoute
  '/projects/$slug/data': typeof ProjectsSlugDataRoute
  '/projects/$slug/deploy': typeof ProjectsSlugDeployRoute
  '/projects/$slug/files': typeof ProjectsSlugFilesRoute
  '/projects/$slug/history': typeof ProjectsSlugHistoryRoute
  '/projects/$slug/integrations': typeof ProjectsSlugIntegrationsRoute
  '/projects/$slug/preview': typeof ProjectsSlugPreviewRoute
  '/projects/$slug/tests': typeof ProjectsSlugTestsRoute
  '/projects/$slug/': typeof ProjectsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/new': typeof NewRoute
  '/providers': typeof ProvidersRoute
  '/projects/$slug/brain': typeof ProjectsSlugBrainRoute
  '/projects/$slug/builder': typeof ProjectsSlugBuilderRoute
  '/projects/$slug/data': typeof ProjectsSlugDataRoute
  '/projects/$slug/deploy': typeof ProjectsSlugDeployRoute
  '/projects/$slug/files': typeof ProjectsSlugFilesRoute
  '/projects/$slug/history': typeof ProjectsSlugHistoryRoute
  '/projects/$slug/integrations': typeof ProjectsSlugIntegrationsRoute
  '/projects/$slug/preview': typeof ProjectsSlugPreviewRoute
  '/projects/$slug/tests': typeof ProjectsSlugTestsRoute
  '/projects/$slug': typeof ProjectsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/new': typeof NewRoute
  '/providers': typeof ProvidersRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/projects/$slug/brain': typeof ProjectsSlugBrainRoute
  '/projects/$slug/builder': typeof ProjectsSlugBuilderRoute
  '/projects/$slug/data': typeof ProjectsSlugDataRoute
  '/projects/$slug/deploy': typeof ProjectsSlugDeployRoute
  '/projects/$slug/files': typeof ProjectsSlugFilesRoute
  '/projects/$slug/history': typeof ProjectsSlugHistoryRoute
  '/projects/$slug/integrations': typeof ProjectsSlugIntegrationsRoute
  '/projects/$slug/preview': typeof ProjectsSlugPreviewRoute
  '/projects/$slug/tests': typeof ProjectsSlugTestsRoute
  '/projects/$slug/': typeof ProjectsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/new'
    | '/providers'
    | '/projects/$slug'
    | '/projects/$slug/brain'
    | '/projects/$slug/builder'
    | '/projects/$slug/data'
    | '/projects/$slug/deploy'
    | '/projects/$slug/files'
    | '/projects/$slug/history'
    | '/projects/$slug/integrations'
    | '/projects/$slug/preview'
    | '/projects/$slug/tests'
    | '/projects/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/new'
    | '/providers'
    | '/projects/$slug/brain'
    | '/projects/$slug/builder'
    | '/projects/$slug/data'
    | '/projects/$slug/deploy'
    | '/projects/$slug/files'
    | '/projects/$slug/history'
    | '/projects/$slug/integrations'
    | '/projects/$slug/preview'
    | '/projects/$slug/tests'
    | '/projects/$slug'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/new'
    | '/providers'
    | '/projects/$slug'
    | '/projects/$slug/brain'
    | '/projects/$slug/builder'
    | '/projects/$slug/data'
    | '/projects/$slug/deploy'
    | '/projects/$slug/files'
    | '/projects/$slug/history'
    | '/projects/$slug/integrations'
    | '/projects/$slug/preview'
    | '/projects/$slug/tests'
    | '/projects/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  NewRoute: typeof NewRoute
  ProvidersRoute: typeof ProvidersRoute
  ProjectsSlugRoute: typeof ProjectsSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/': {
      id: '/projects/$slug/'
      path: '/'
      fullPath: '/projects/$slug/'
      preLoaderRoute: typeof ProjectsSlugIndexRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/brain': {
      id: '/projects/$slug/brain'
      path: '/brain'
      fullPath: '/projects/$slug/brain'
      preLoaderRoute: typeof ProjectsSlugBrainRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/builder': {
      id: '/projects/$slug/builder'
      path: '/builder'
      fullPath: '/projects/$slug/builder'
      preLoaderRoute: typeof ProjectsSlugBuilderRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/data': {
      id: '/projects/$slug/data'
      path: '/data'
      fullPath: '/projects/$slug/data'
      preLoaderRoute: typeof ProjectsSlugDataRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/deploy': {
      id: '/projects/$slug/deploy'
      path: '/deploy'
      fullPath: '/projects/$slug/deploy'
      preLoaderRoute: typeof ProjectsSlugDeployRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/files': {
      id: '/projects/$slug/files'
      path: '/files'
      fullPath: '/projects/$slug/files'
      preLoaderRoute: typeof ProjectsSlugFilesRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/history': {
      id: '/projects/$slug/history'
      path: '/history'
      fullPath: '/projects/$slug/history'
      preLoaderRoute: typeof ProjectsSlugHistoryRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/integrations': {
      id: '/projects/$slug/integrations'
      path: '/integrations'
      fullPath: '/projects/$slug/integrations'
      preLoaderRoute: typeof ProjectsSlugIntegrationsRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/preview': {
      id: '/projects/$slug/preview'
      path: '/preview'
      fullPath: '/projects/$slug/preview'
      preLoaderRoute: typeof ProjectsSlugPreviewRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
    '/projects/$slug/tests': {
      id: '/projects/$slug/tests'
      path: '/tests'
      fullPath: '/projects/$slug/tests'
      preLoaderRoute: typeof ProjectsSlugTestsRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
  }
}

interface ProjectsSlugRouteChildren {
  ProjectsSlugBrainRoute: typeof ProjectsSlugBrainRoute
  ProjectsSlugBuilderRoute: typeof ProjectsSlugBuilderRoute
  ProjectsSlugDataRoute: typeof ProjectsSlugDataRoute
  ProjectsSlugDeployRoute: typeof ProjectsSlugDeployRoute
  ProjectsSlugFilesRoute: typeof ProjectsSlugFilesRoute
  ProjectsSlugHistoryRoute: typeof ProjectsSlugHistoryRoute
  ProjectsSlugIntegrationsRoute: typeof ProjectsSlugIntegrationsRoute
  ProjectsSlugPreviewRoute: typeof ProjectsSlugPreviewRoute
  ProjectsSlugTestsRoute: typeof ProjectsSlugTestsRoute
  ProjectsSlugIndexRoute: typeof ProjectsSlugIndexRoute
}

const ProjectsSlugRouteChildren: ProjectsSlugRouteChildren = {
  ProjectsSlugBrainRoute: ProjectsSlugBrainRoute,
  ProjectsSlugBuilderRoute: ProjectsSlugBuilderRoute,
  ProjectsSlugDataRoute: ProjectsSlugDataRoute,
  ProjectsSlugDeployRoute: ProjectsSlugDeployRoute,
  ProjectsSlugFilesRoute: ProjectsSlugFilesRoute,
  ProjectsSlugHistoryRoute: ProjectsSlugHistoryRoute,
  ProjectsSlugIntegrationsRoute: ProjectsSlugIntegrationsRoute,
  ProjectsSlugPreviewRoute: ProjectsSlugPreviewRoute,
  ProjectsSlugTestsRoute: ProjectsSlugTestsRoute,
  ProjectsSlugIndexRoute: ProjectsSlugIndexRoute,
}

const ProjectsSlugRouteWithChildren = ProjectsSlugRoute._addFileChildren(
  ProjectsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  NewRoute: NewRoute,
  ProvidersRoute: ProvidersRoute,
  ProjectsSlugRoute: ProjectsSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
